name = "my-blog"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "rijiben-db"          # 请改成您在 D1 中创建的数据库名称
database_id = "06ad87d3-5679-4aff-aae1-480706d723b2"        # 在 Cloudflare Dashboard 中获取
